### ISSUE TITLE
Error: cannot open file: nimjson

### ISSUE THREAD

**Issue by mrhdias** [jiro4989/nimjson#1]
I installed the library as suggested here: nimble install nimjson

I tried to use the API example but it does not work!

```nim
import nimjson
import json

echo """{"keyStr":"str", "keyInt":1}""".parseJson().toTypeString()
echo "examples/primitive.json".parseFile().toTypeString("testObject")
```

$ nim c -r test.nim
Hint: used config file '/home/hdias/.choosenim/toolchains/nim-0.20.0/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: test [Processing]
/home/hdias/tmp/test.nim(1, 8) Error: cannot open file: nimjson

**Comment by jiro4989** [comment]
@mrhdias Thx, I will fix this problem.

**Comment by jiro4989** [comment]
@mrhdias I fixed this problem. Please re-test yourself.
