### ISSUE TITLE
Duplicate types generated

### ISSUE THREAD

**Issue by geotre** [jiro4989/nimjson#26]
I have a large json file where there are several duplicated keys, for different objects. This generates Nim types that clash as they have the same name.

Here's a minimal reproduction:

```json
{
  "obj1": {
    "subtype": {"a": 1}
  },
  "obj2": {
    "subtype": {"b": 1}
  }
}
```

Running `nimjson test.json` gives this output:

```nim
type
  NilType = ref object
  Object = ref object
    obj1: Obj1
    obj2: Obj2
  Obj1 = ref object
    subtype: Subtype
  Subtype = ref object
    a: int64
  Obj2 = ref object
    subtype: Subtype
  Subtype = ref object
    b: int64
```

It is not valid nim due to the repeated `Subtype` declarations. I can obviously fix this manually but it would be nice if it generated them as `Subtype1`, `Subtype2`, etc.

**Comment by geotre** [comment]
I've also just noticed that there is a similar related case:

```json
{
  "obj1": {
    "subtype": {"a": 1}
  },
  "obj2": {
    "subtype": {"a": 1}
  }
}
```
Generates two identical `Subtype` types, where they could be reduced to one with no renaming needed

**Comment by jiro4989** [comment]
> I have a large json file where there are several duplicated keys, for different objects. This generates Nim types that clash as they have the same name.
> 
> Here's a minimal reproduction:
> 
> ```json
> {
>   "obj1": {
>     "subtype": {"a": 1}
>   },
>   "obj2": {
>     "subtype": {"b": 1}
>   }
> }
> ```
> 
> Running `nimjson test.json` gives this output:
> 
> ```nim
> type
>   NilType = ref object
>   Object = ref object
>     obj1: Obj1
>     obj2: Obj2
>   Obj1 = ref object
>     subtype: Subtype
>   Subtype = ref object
>     a: int64
>   Obj2 = ref object
>     subtype: Subtype
>   Subtype = ref object
>     b: int64
> ```
> 
> It is not valid nim due to the repeated `Subtype` declarations. I can obviously fix this manually but it would be nice if it generated them as `Subtype1`, `Subtype2`, etc.

Fixed.



```bash
$ cat a.json
{
  "obj1": {
    "subtype": {"a": 1}
  },
  "obj2": {
    "subtype": {"b": 1}
  }
}

$ cat a.json | nimjson
type
  NilType = ref object
  Object = ref object
    obj1: Obj1
    obj2: Obj2
  Obj1 = ref object
    subtype: Subtype
  Subtype = ref object
    a: int64
  Obj2 = ref object
    subtype: Subtype2
  Subtype2 = ref object
    b: int64
```

**Comment by jiro4989** [comment]
@geotre 

> I've also just noticed that there is a similar related case:
> 
> ```json
> {
>   "obj1": {
>     "subtype": {"a": 1}
>   },
>   "obj2": {
>     "subtype": {"a": 1}
>   }
> }
> ```
> 
> Generates two identical `Subtype` types, where they could be reduced to one with no renaming needed

This will be breaking changes.

I will add a new option to `nimjson` (ex: `--merge-duplicated-object`, default false) to fix this problem.

**Comment by jiro4989** [comment]
> @geotre
> 
> > I've also just noticed that there is a similar related case:
> > ```json
> > {
> >   "obj1": {
> >     "subtype": {"a": 1}
> >   },
> >   "obj2": {
> >     "subtype": {"a": 1}
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Generates two identical `Subtype` types, where they could be reduced to one with no renaming needed
> 
> This will be breaking changes.
> 
> I will add a new option to `nimjson` (ex: `--merge-duplicated-object`, default false) to fix this problem.

I don't want to implement this, because of programs increase complexity and I don't need this feature.
